= q-cli-jlink

Sample Quarkus CLI application (packaged with jlink)

Shows how a link:https://quarkus.io/[Quarkus] application may be configured and packaged to create cross-platform
custom Java Runtimes with jlink, package each JR as a zip distribution and publish them as assets on a Git release
via link:https://jreleaser.org[JReleaser].

== Prerequisites

This sample requires features from JReleaser `v0.9.0-SNAPSHOT` (unreleased).
You must build and install your own snapshot first.

WARNING: You need Java 11 to build JReleaser. It might work with other versions up to 15 but no greater than 15.

.Steps
1. `git clone https://github.com/jreleaser/jreleaser.git`
2. `cd jreleaser`
3. `./gradlew publishToMavenLocal`

== Building & Assembling

WARNING: Java 11 is required to build this sample. You can not use a greater version, it must be exactly 11 or any
of its updates.

`$ ./mvnw -Passemble package`

Inspect the artifacts found at `target/jreleaser/assemble/q-cli/jlink` and run one:

`$ target/jreleaser/assemble/q-cli/jlink/work-linux-x86_64/q-cli-0.1.0-linux-x86_64/bin/q-cli`

== Releasing

WARNING: Requires a GitHub token for publishing a release to GitHub.

1. Create a GitHub Personal Access Token.
See link:https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token[Creating a personal access token]
for instructions.
2. Store the token as an environment variable (`JRELEASER_GITHUB_TOKEN`) or save it at a configuration file as explained
at link:https://jreleaser.org/guide/latest/configuration/environment.html[JReleaser's environment settings].

Posting a release from a local environment

.Display configuration
`$ ./mvnw -Prelease jreleaser:config`

.Dryrun mode
`$ ./mvnw -Prelease jreleaser:release -Djreleaser.dryrun=true`

.For production
`$ ./mvnw -Prelease jreleaser:release`

Inspect additional artifacts found at `target/jreleaser`:

```
target/jreleaser/
├── output.properties
├── release
│   └── CHANGELOG.md
└── trace.log
```
